### ISSUE TITLE
Add ensemble member to file name for remote import

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/nwpconf#2]
File remotely copied for import into archive by `putarki_archive` (`putarki.sh`) should add ensemble member information to pid `$$` in file name to avoid race conditions (e.g. in case of same pid on different nodes):

```
            scp $file $ARKI_IMPSSH:$ARKI_IMPDIR/.$dest.$$.$DATE$TIME.$tf
            ssh $ARKI_IMPSSH mv -f $ARKI_IMPDIR/.$dest.$$.$DATE$TIME.$tf $ARKI_IMPDIR/$dest.$$.$DATE$TIME.$tf
            echo $ARKI_IMPDIR/$dest.$$.$DATE$TIME.$tf;;
```
Check also import scripts for correct parsing of file name (cron package).

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.

**Comment by dcesari** [comment]
Il metodo `putarcki_archive` è obsoleto e sostituito da `putarki_configured_archive` che tiene conto del membro dell'ensemble, possiamo dormire tranquilli.
