### ISSUE TITLE
Split observations for bufr conversion

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/nwpconf#3]
Observational datasets defined in `$BUFR_ARKI_DS` retrieved from archive in `getarki_obsbufr` function of `getarki.sh` should be split into 2 sets, to be retrieved in 2 different files, one to be converted by `dbamsg convert` (e.g. old synop and temp, maybe new amdar) and the other not to be converted.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
