### ISSUE TITLE
Sete $DATE and $TIME in radar mosaico loop

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/nwpconf#4]
When looping on different time levels in functions `simc_convert_radar_grib` and `simc_create_radar_grib`, in `simc_site.sh`, the variables `$DATE` and `$TIME` are not set, thus leading to file names for arki-scan not containing the current date and time.

**Comment by edigiacomo** [comment]
Questa issue è stata chiusa per inattività. Nel caso in cui sia un argomento ancora rilevante, si prega di riaprirla con una motivazione che tenga conto delle modifiche applicate nel corso degli anni al progetto.
